project:
  type: website
  output-dir: docs
  
execute:
  cache: true
  freeze: auto
  warning: false

website:
  title: "FIP606"
  favicon: logo.png
  
  navbar:
    pinned: true
    logo: logo.png
    
    left:
      - text: R Básico
        menu: 
        - href: Aula 1.qmd
          text: Para que serve o R?
        - href: Aula 1b.qmd
          text: Instalação do R e RStudio
        - href: Aula 2.qmd
          text: Introdução ao R


     
    right:
       - icon: linkedin
         href: https://www.linkedin.com/in/lucasversari/
       - icon: instagram
         menu: 
            - text: Lucas Versari
              url: https://www.instagram.com/lucasversari/
            - text: Emerson M. Del Ponte
              url: https://www.instagram.com/emdelponte/
            - text: Fitopatolofia UFV
              url: https://www.instagram.com/fitopatologiaufv/
       - icon: Lattes 
         menu:
            - text: Curriculo Lattes
              url: http://lattes.cnpq.br/4019652817990249
       - icon: github
         menu:
            - text: Lucas R. Versari
              url: https://lversari.github.io/FIP606_2024/
            - text: Emerson M. Del Ponte
              url: https://github.com/emdelponte
  
  back-to-top-navigation: true

format:
  html:
    theme: 
      light: flatly
      dark: superhero
    css: styles.css
    toc: true

editor: visual

      
