project:
  type: website
  output-dir: docs

website:
  title: "FIP606_2024"
  navbar:
    left:
      - href: index.qmd
      - href: Aula 1.qmd
        text: R Básico

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

      
